name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 988197903609.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker images
        run: |
          docker build -t my-backend:latest ./backend

          docker build -f ./backend/Dockerfile.worker -t my-worker:latest ./backend

      - name: Tag & Push
        run: |
          docker tag my-backend:latest 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest
          docker push 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest

          docker tag my-worker:latest 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-worker:latest
          docker push 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-worker:latest

      - name: SSH to EC2 & Run Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SECRETS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Login to ECR
            aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin 988197903609.dkr.ecr.us-east-1.amazonaws.com

            docker pull 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest
            docker pull 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-worker:latest || true
            docker pull redis:7
            docker pull nginx:alpine

            docker stop backend || true
            docker stop worker || true
            docker stop redis || true
            docker stop nginx || true

            docker rm backend || true
            docker rm worker || true
            docker rm redis || true
            docker rm nginx || true

            docker run -d --name redis -p 6379:6379 redis:7

            docker run -d --name backend -p 8501:8501 --env-file /home/ubuntu/.env 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-backend:latest

            docker run -d --name worker --env-file /home/ubuntu/.env 988197903609.dkr.ecr.us-east-1.amazonaws.com/my-worker:latest || true

            docker run -d --name nginx -p 80:80 -v /home/ubuntu/frontend:/usr/share/nginx/html nginx:alpine
